- name: Run setup tasks
  hosts: all
  tasks:
  - include_tasks: tasks/linux.yml
    when: ansible_system == "Linux"

  - include_tasks: tasks/windows.yml
    when: ansible_os_family == "Windows"

  - include_tasks: tasks/freebsd.yml
    when: ansible_system == "FreeBSD"

  - include_tasks: tasks/macos.yml
    when: ansible_system == "Darwin"

  handlers:
  - name: Perform reboot (Windows)
    listen: reboot
    win_reboot:
    when: ansible_os_family == "Windows"
  - name: Perform reboot (non-Windows)
    listen: reboot
    reboot:
    when: ansible_os_family != "Windows"
